import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import '../models/message.dart';

class ReportService {
  static Future<void> generateAndShare(
      List<ChatMessage> messages, String role) async {
    final doc = pw.Document();

    final titleStyle = pw.TextStyle(
      fontSize: 20,
      fontWeight: pw.FontWeight.bold,
      color: PdfColors.blue900,
    );
    final headerStyle = pw.TextStyle(
      fontSize: 14,
      fontWeight: pw.FontWeight.bold,
      color: PdfColors.blue800,
    );
    final bodyStyle = const pw.TextStyle(fontSize: 11);
    final mutedStyle = pw.TextStyle(fontSize: 10, color: PdfColors.grey600);

    final now = DateTime.now();
    final dateStr =
        '${now.year}-${now.month.toString().padLeft(2, '0')}-${now.day.toString().padLeft(2, '0')}';

    doc.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(40),
        build: (ctx) => [
          pw.Text('Medical Consultation Report', style: titleStyle),
          pw.SizedBox(height: 4),
          pw.Text('Date: $dateStr  |  Role: ${role[0].toUpperCase()}${role.substring(1)}',
              style: mutedStyle),
          pw.Divider(thickness: 1, color: PdfColors.blue200),
          pw.SizedBox(height: 12),

          pw.Text('Conversation', style: headerStyle),
          pw.SizedBox(height: 8),

          ...messages
              .where((m) => m.content.isNotEmpty)
              .map((m) => pw.Container(
                    margin: const pw.EdgeInsets.only(bottom: 10),
                    padding: const pw.EdgeInsets.all(10),
                    decoration: pw.BoxDecoration(
                      color: m.isUser ? PdfColors.blue50 : PdfColors.grey100,
                      borderRadius: pw.BorderRadius.circular(6),
                      border: pw.Border.all(
                        color: m.isUser ? PdfColors.blue200 : PdfColors.grey300,
                      ),
                    ),
                    child: pw.Column(
                      crossAxisAlignment: pw.CrossAxisAlignment.start,
                      children: [
                        pw.Text(
                          m.isUser ? 'Patient / User' : 'AI Medical Assistant',
                          style: pw.TextStyle(
                            fontSize: 10,
                            fontWeight: pw.FontWeight.bold,
                            color: m.isUser
                                ? PdfColors.blue800
                                : PdfColors.grey700,
                          ),
                        ),
                        pw.SizedBox(height: 4),
                        pw.Text(m.content, style: bodyStyle),
                        if (m.severity != null) ...[
                          pw.SizedBox(height: 4),
                          pw.Text('Severity: ${m.severity}',
                              style: pw.TextStyle(
                                fontSize: 10,
                                color: _severityColor(m.severity!),
                                fontWeight: pw.FontWeight.bold,
                              )),
                        ],
                      ],
                    ),
                  )),

          pw.SizedBox(height: 20),
          pw.Divider(color: PdfColors.grey300),
          pw.SizedBox(height: 8),
          pw.Text(
            'Disclaimer: This report is generated by an AI medical assistant for informational purposes only. '
            'It does not constitute a medical diagnosis or professional advice. '
            'Always consult a qualified healthcare professional.',
            style: mutedStyle,
          ),
        ],
      ),
    );

    await Printing.sharePdf(
      bytes: await doc.save(),
      filename: 'medical_report_$dateStr.pdf',
    );
  }

  static PdfColor _severityColor(String severity) {
    switch (severity) {
      case 'severe':
        return PdfColors.red700;
      case 'moderate':
        return PdfColors.orange700;
      default:
        return PdfColors.green700;
    }
  }
}
