import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import '../models/message.dart';

bool _containsArabic(String text) {
  return text.runes.any((r) => r >= 0x0600 && r <= 0x06FF);
}

/// Splits long text into individual paragraph widgets so no single widget
/// exceeds a page height (pw.Text is not a spanning widget).
List<pw.Widget> _textParagraphs(
  String text, {
  required pw.Font? font,
  required double fontSize,
  PdfColor? color,
}) {
  final dir =
      _containsArabic(text) ? pw.TextDirection.rtl : pw.TextDirection.ltr;
  final style = pw.TextStyle(font: font, fontSize: fontSize, color: color);

  final lines = text
      .split('\n')
      .map((l) => l.trim())
      .where((l) => l.isNotEmpty)
      .toList();

  if (lines.isEmpty) {
    return [pw.Text(text, style: style, textDirection: dir)];
  }

  return lines
      .map((line) => pw.Text(line, style: style, textDirection: dir)
          as pw.Widget)
      .toList();
}

class ReportService {
  static Future<void> generateAndShare(
      List<ChatMessage> messages, String role) async {
    final doc = pw.Document();

    // Try to load Arabic-supporting font; fall back gracefully if offline
    pw.Font? arabicFont;
    pw.Font? arabicFontBold;
    try {
      arabicFont = await PdfGoogleFonts.cairoRegular();
      arabicFontBold = await PdfGoogleFonts.cairoBold();
    } catch (_) {
      // No internet — English will still render fine with default font
    }

    final now = DateTime.now();
    final dateStr =
        '${now.year}-${now.month.toString().padLeft(2, '0')}-${now.day.toString().padLeft(2, '0')}';

    final List<pw.Widget> content = [
      pw.Text(
        'Medical Consultation Report',
        style: pw.TextStyle(
          font: arabicFontBold,
          fontSize: 20,
          fontWeight: pw.FontWeight.bold,
          color: PdfColors.blue900,
        ),
      ),
      pw.SizedBox(height: 4),
      pw.Text(
        'Date: $dateStr  |  Role: ${role[0].toUpperCase()}${role.substring(1)}',
        style: pw.TextStyle(font: arabicFont, fontSize: 10, color: PdfColors.grey600),
      ),
      pw.Divider(thickness: 1, color: PdfColors.blue200),
      pw.SizedBox(height: 12),
      pw.Text(
        'Conversation',
        style: pw.TextStyle(
          font: arabicFontBold,
          fontSize: 14,
          fontWeight: pw.FontWeight.bold,
          color: PdfColors.blue800,
        ),
      ),
      pw.SizedBox(height: 8),
    ];

    for (final m in messages.where((m) => m.content.isNotEmpty)) {
      // Sender label
      content.add(pw.Text(
        m.isUser ? 'Patient / User:' : 'AI Medical Assistant:',
        style: pw.TextStyle(
          font: arabicFontBold,
          fontSize: 10,
          fontWeight: pw.FontWeight.bold,
          color: m.isUser ? PdfColors.blue800 : PdfColors.grey700,
        ),
      ));
      content.add(pw.SizedBox(height: 2));

      // Message body — split into paragraphs to avoid page-overflow
      content.addAll(_textParagraphs(
        m.content,
        font: arabicFont,
        fontSize: 11,
        color: m.isUser ? PdfColors.blue900 : PdfColors.grey900,
      ));

      if (m.severity != null) {
        content.add(pw.SizedBox(height: 2));
        content.add(pw.Text(
          'Severity: ${m.severity}',
          style: pw.TextStyle(
            font: arabicFontBold,
            fontSize: 10,
            color: _severityColor(m.severity!),
            fontWeight: pw.FontWeight.bold,
          ),
        ));
      }

      content.add(pw.Divider(color: PdfColors.grey200, thickness: 0.5));
      content.add(pw.SizedBox(height: 4));
    }

    content.addAll([
      pw.SizedBox(height: 16),
      pw.Divider(color: PdfColors.grey300),
      pw.SizedBox(height: 8),
      pw.Text(
        'Disclaimer: This report is generated by an AI medical assistant for informational purposes only. '
        'It does not constitute a medical diagnosis or professional advice. '
        'Always consult a qualified healthcare professional.',
        style: pw.TextStyle(font: arabicFont, fontSize: 10, color: PdfColors.grey600),
      ),
    ]);

    doc.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(40),
        build: (ctx) => content,
      ),
    );

    await Printing.sharePdf(
      bytes: await doc.save(),
      filename: 'medical_report_$dateStr.pdf',
    );
  }

  static PdfColor _severityColor(String severity) {
    switch (severity) {
      case 'severe':
        return PdfColors.red700;
      case 'moderate':
        return PdfColors.orange700;
      default:
        return PdfColors.green700;
    }
  }
}
