"""
Static data for doctors and medicines.
Update these lists to change what appears in the app.
"""

DOCTORS = [
    {
        "id": "d1",
        "name": "Dr. Ahmed Hassan",
        "specialty": "Cardiologist",
        "image_url": "https://randomuser.me/api/portraits/men/32.jpg",
        "available_times": ["9:00 AM", "11:00 AM", "2:00 PM", "5:00 PM"],
        "rating": 4.9,
        "experience_years": 15,
        "price": 200,
        "hospital": "Cairo Heart Center",
        "about": "Specialist in cardiovascular diseases and interventional cardiology with 15 years of clinical experience.",
    },
    {
        "id": "d2",
        "name": "Dr. Mona Khalil",
        "specialty": "Dermatologist",
        "image_url": "https://randomuser.me/api/portraits/women/44.jpg",
        "available_times": ["10:00 AM", "1:00 PM", "3:30 PM"],
        "rating": 4.7,
        "experience_years": 10,
        "price": 150,
        "hospital": "Skin & Beauty Clinic",
        "about": "Expert in medical and cosmetic dermatology. Treats acne, eczema, psoriasis, and more.",
    },
    {
        "id": "d3",
        "name": "Dr. Omar Sayed",
        "specialty": "General Practitioner",
        "image_url": "https://randomuser.me/api/portraits/men/55.jpg",
        "available_times": ["8:00 AM", "10:00 AM", "12:00 PM", "3:00 PM", "6:00 PM"],
        "rating": 4.6,
        "experience_years": 8,
        "price": 100,
        "hospital": "Family Health Clinic",
        "about": "Primary care physician handling all general health concerns, check-ups, and referrals.",
    },
    {
        "id": "d4",
        "name": "Dr. Nadia Mostafa",
        "specialty": "Pediatrician",
        "image_url": "https://randomuser.me/api/portraits/women/28.jpg",
        "available_times": ["9:30 AM", "11:30 AM", "2:30 PM"],
        "rating": 4.8,
        "experience_years": 12,
        "price": 175,
        "hospital": "Children's Medical Center",
        "about": "Dedicated to children's health from newborns to teenagers. Vaccination and developmental specialist.",
    },
    {
        "id": "d5",
        "name": "Dr. Karim Ibrahim",
        "specialty": "Orthopedist",
        "image_url": "https://randomuser.me/api/portraits/men/62.jpg",
        "available_times": ["10:00 AM", "1:00 PM", "4:00 PM"],
        "rating": 4.7,
        "experience_years": 13,
        "price": 180,
        "hospital": "National Orthopedic Hospital",
        "about": "Bone, joint, and sports injury specialist. Provides surgical and non-surgical treatments.",
    },
    {
        "id": "d6",
        "name": "Dr. Yasmine Farouk",
        "specialty": "Neurologist",
        "image_url": "https://randomuser.me/api/portraits/women/61.jpg",
        "available_times": ["11:00 AM", "2:00 PM", "5:00 PM"],
        "rating": 4.9,
        "experience_years": 17,
        "price": 220,
        "hospital": "Neurology & Brain Institute",
        "about": "Expert in neurological disorders including migraines, epilepsy, stroke, and Parkinson's disease.",
    },
    {
        "id": "d7",
        "name": "Dr. Hossam Ramzy",
        "specialty": "Psychiatrist",
        "image_url": "https://randomuser.me/api/portraits/men/47.jpg",
        "available_times": ["10:00 AM", "12:30 PM", "3:00 PM", "5:30 PM"],
        "rating": 4.8,
        "experience_years": 11,
        "price": 200,
        "hospital": "Mental Wellness Center",
        "about": "Specialist in mental health, anxiety, depression, OCD, and addiction therapy.",
    },
    {
        "id": "d8",
        "name": "Dr. Sara Eldin",
        "specialty": "Gynecologist",
        "image_url": "https://randomuser.me/api/portraits/women/36.jpg",
        "available_times": ["9:00 AM", "11:00 AM", "2:00 PM"],
        "rating": 4.8,
        "experience_years": 14,
        "price": 190,
        "hospital": "Women's Health Center",
        "about": "Women's health specialist covering obstetrics, fertility, and gynecological care.",
    },
    {
        "id": "d9",
        "name": "Dr. Tarek Sobhy",
        "specialty": "Ophthalmologist",
        "image_url": "https://randomuser.me/api/portraits/men/71.jpg",
        "available_times": ["8:30 AM", "11:00 AM", "1:30 PM", "4:00 PM"],
        "rating": 4.7,
        "experience_years": 16,
        "price": 180,
        "hospital": "Eye Care Institute",
        "about": "Specialist in eye diseases, LASIK, cataract surgery, and retinal disorders.",
    },
    {
        "id": "d10",
        "name": "Dr. Laila Saad",
        "specialty": "Endocrinologist",
        "image_url": "https://randomuser.me/api/portraits/women/58.jpg",
        "available_times": ["10:00 AM", "12:00 PM", "3:00 PM"],
        "rating": 4.9,
        "experience_years": 18,
        "price": 230,
        "hospital": "Endocrine & Diabetes Center",
        "about": "Expert in diabetes management, thyroid disorders, hormonal imbalances, and metabolic conditions.",
    },
    {
        "id": "d11",
        "name": "Dr. Amr Badr",
        "specialty": "ENT Specialist",
        "image_url": "https://randomuser.me/api/portraits/men/83.jpg",
        "available_times": ["9:00 AM", "11:30 AM", "2:30 PM", "5:00 PM"],
        "rating": 4.6,
        "experience_years": 9,
        "price": 140,
        "hospital": "ENT & Allergy Clinic",
        "about": "Ear, nose, and throat specialist treating sinusitis, hearing loss, tonsillitis, and vocal cord conditions.",
    },
    {
        "id": "d12",
        "name": "Dr. Hana Wahba",
        "specialty": "Rheumatologist",
        "image_url": "https://randomuser.me/api/portraits/women/74.jpg",
        "available_times": ["10:00 AM", "1:00 PM", "4:00 PM"],
        "rating": 4.8,
        "experience_years": 12,
        "price": 210,
        "hospital": "Arthritis & Joint Center",
        "about": "Specialist in rheumatoid arthritis, lupus, gout, and autoimmune joint diseases.",
    },
    {
        "id": "d13",
        "name": "Dr. Sherif Nour",
        "specialty": "Gastroenterologist",
        "image_url": "https://randomuser.me/api/portraits/men/90.jpg",
        "available_times": ["8:00 AM", "10:30 AM", "1:00 PM", "3:30 PM"],
        "rating": 4.7,
        "experience_years": 13,
        "price": 195,
        "hospital": "Digestive Health Center",
        "about": "Expert in IBS, GERD, liver disease, endoscopy, and colonoscopy procedures.",
    },
    {
        "id": "d14",
        "name": "Dr. Dina Rashad",
        "specialty": "Pulmonologist",
        "image_url": "https://randomuser.me/api/portraits/women/87.jpg",
        "available_times": ["9:30 AM", "12:00 PM", "3:30 PM"],
        "rating": 4.7,
        "experience_years": 10,
        "price": 175,
        "hospital": "Chest & Respiratory Clinic",
        "about": "Specialist in asthma, COPD, sleep apnea, bronchitis, and pulmonary function tests.",
    },
    {
        "id": "d15",
        "name": "Dr. Khaled Atef",
        "specialty": "Urologist",
        "image_url": "https://randomuser.me/api/portraits/men/78.jpg",
        "available_times": ["10:00 AM", "12:30 PM", "4:00 PM", "6:00 PM"],
        "rating": 4.6,
        "experience_years": 11,
        "price": 185,
        "hospital": "Urology & Kidney Center",
        "about": "Expert in kidney stones, UTIs, prostate conditions, and minimally invasive urological surgery.",
    },
    {
        "id": "d16",
        "name": "Dr. Maha Osman",
        "specialty": "Oncologist",
        "image_url": "https://randomuser.me/api/portraits/women/90.jpg",
        "available_times": ["11:00 AM", "2:00 PM", "5:00 PM"],
        "rating": 4.9,
        "experience_years": 20,
        "price": 350,
        "hospital": "National Cancer Institute",
        "about": "Senior oncologist specializing in breast, colorectal, and lung cancers with comprehensive treatment plans.",
    },
    {
        "id": "d17",
        "name": "Dr. Samer Awad",
        "specialty": "Nephrologist",
        "image_url": "https://randomuser.me/api/portraits/men/95.jpg",
        "available_times": ["9:00 AM", "11:30 AM", "2:00 PM"],
        "rating": 4.8,
        "experience_years": 15,
        "price": 220,
        "hospital": "Kidney Care Center",
        "about": "Specialist in chronic kidney disease, dialysis management, hypertensive nephropathy, and kidney transplant follow-up.",
    },
    {
        "id": "d18",
        "name": "Dr. Rania Khalaf",
        "specialty": "Allergist",
        "image_url": "https://randomuser.me/api/portraits/women/96.jpg",
        "available_times": ["8:30 AM", "10:30 AM", "1:30 PM", "4:30 PM"],
        "rating": 4.7,
        "experience_years": 8,
        "price": 155,
        "hospital": "Allergy & Immunology Clinic",
        "about": "Expert in food allergies, eczema, hay fever, urticaria, and immunotherapy treatments.",
    },
]

APPOINTMENTS = [
    {
        "id": "a1",
        "patient_name": "Mohamed Ali",
        "patient_age": 45,
        "doctor_id": "d1",
        "doctor_name": "Dr. Ahmed Hassan",
        "specialty": "Cardiologist",
        "date": "2026-04-02",
        "time": "9:00 AM",
        "status": "confirmed",
        "notes": "Follow-up for hypertension management",
        "patient_image": "https://randomuser.me/api/portraits/men/10.jpg",
    },
    {
        "id": "a2",
        "patient_name": "Fatima Samir",
        "patient_age": 32,
        "doctor_id": "d1",
        "doctor_name": "Dr. Ahmed Hassan",
        "specialty": "Cardiologist",
        "date": "2026-04-02",
        "time": "11:00 AM",
        "status": "pending",
        "notes": "New patient — chest pain evaluation",
        "patient_image": "https://randomuser.me/api/portraits/women/12.jpg",
    },
    {
        "id": "a3",
        "patient_name": "Khaled Mansour",
        "patient_age": 58,
        "doctor_id": "d1",
        "doctor_name": "Dr. Ahmed Hassan",
        "specialty": "Cardiologist",
        "date": "2026-04-03",
        "time": "2:00 PM",
        "status": "confirmed",
        "notes": "Annual cardiac check-up",
        "patient_image": "https://randomuser.me/api/portraits/men/21.jpg",
    },
    {
        "id": "a4",
        "patient_name": "Nour Hamdy",
        "patient_age": 27,
        "doctor_id": "d2",
        "doctor_name": "Dr. Mona Khalil",
        "specialty": "Dermatologist",
        "date": "2026-04-02",
        "time": "10:00 AM",
        "status": "confirmed",
        "notes": "Acne treatment follow-up",
        "patient_image": "https://randomuser.me/api/portraits/women/33.jpg",
    },
    {
        "id": "a5",
        "patient_name": "Ahmed Tarek",
        "patient_age": 34,
        "doctor_id": "d3",
        "doctor_name": "Dr. Omar Sayed",
        "specialty": "General Practitioner",
        "date": "2026-04-01",
        "time": "8:00 AM",
        "status": "completed",
        "notes": "Routine check-up and blood work review",
        "patient_image": "https://randomuser.me/api/portraits/men/15.jpg",
    },
]

PENDING_PATIENTS = [
    {
        "id": "pp1",
        "name": "Sara Wael",
        "age": 29,
        "symptoms": "Severe headache, dizziness, blurred vision",
        "priority": "high",
        "wait_time": "5 min",
        "image": "https://randomuser.me/api/portraits/women/22.jpg",
    },
    {
        "id": "pp2",
        "name": "Hassan Youssef",
        "age": 52,
        "symptoms": "Chest tightness, shortness of breath",
        "priority": "high",
        "wait_time": "12 min",
        "image": "https://randomuser.me/api/portraits/men/40.jpg",
    },
    {
        "id": "pp3",
        "name": "Dina Kamal",
        "age": 38,
        "symptoms": "Persistent cough, mild fever",
        "priority": "medium",
        "wait_time": "20 min",
        "image": "https://randomuser.me/api/portraits/women/50.jpg",
    },
    {
        "id": "pp4",
        "name": "Omar Fathy",
        "age": 19,
        "symptoms": "Skin rash, itching",
        "priority": "low",
        "wait_time": "35 min",
        "image": "https://randomuser.me/api/portraits/men/68.jpg",
    },
]

MEDICINES = [
    {
        "id": "m1",
        "name": "Paracetamol 500mg",
        "category": "Pain Relief",
        "price": 12.50,
        "description": "Effective pain relief and fever reducer. Suitable for adults and children over 12.",
        "image_url": "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=300&q=80",
        "in_stock": True,
        "requires_prescription": False,
        "quantity_available": 150,
    },
    {
        "id": "m2",
        "name": "Ibuprofen 400mg",
        "category": "Pain Relief",
        "price": 18.00,
        "description": "Anti-inflammatory pain reliever. Effective for headaches, muscle pain, and fever.",
        "image_url": "https://images.unsplash.com/photo-1550572017-edd951aa8f72?w=300&q=80",
        "in_stock": True,
        "requires_prescription": False,
        "quantity_available": 90,
    },
    {
        "id": "m3",
        "name": "Amoxicillin 500mg",
        "category": "Antibiotics",
        "price": 35.00,
        "description": "Broad-spectrum antibiotic for bacterial infections of ear, nose, throat, and chest.",
        "image_url": "https://images.unsplash.com/photo-1631549916768-4119b2e5f926?w=300&q=80",
        "in_stock": True,
        "requires_prescription": True,
        "quantity_available": 60,
    },
    {
        "id": "m4",
        "name": "Azithromycin 250mg",
        "category": "Antibiotics",
        "price": 55.00,
        "description": "Antibiotic for respiratory and skin infections. 5-day treatment course.",
        "image_url": "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=300&q=80",
        "in_stock": True,
        "requires_prescription": True,
        "quantity_available": 40,
    },
    {
        "id": "m5",
        "name": "Vitamin C 1000mg",
        "category": "Vitamins",
        "price": 25.00,
        "description": "Immune system booster and powerful antioxidant. Effervescent tablet.",
        "image_url": "https://images.unsplash.com/photo-1619566636858-adf3ef46400b?w=300&q=80",
        "in_stock": True,
        "requires_prescription": False,
        "quantity_available": 200,
    },
    {
        "id": "m6",
        "name": "Vitamin D3 5000 IU",
        "category": "Vitamins",
        "price": 40.00,
        "description": "Essential for bone health and immune function. Daily supplement.",
        "image_url": "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=300&q=80",
        "in_stock": True,
        "requires_prescription": False,
        "quantity_available": 120,
    },
    {
        "id": "m7",
        "name": "Omeprazole 20mg",
        "category": "Digestive",
        "price": 22.00,
        "description": "Proton pump inhibitor for acid reflux, heartburn, and stomach ulcers.",
        "image_url": "https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=300&q=80",
        "in_stock": True,
        "requires_prescription": False,
        "quantity_available": 80,
    },
    {
        "id": "m8",
        "name": "Metformin 500mg",
        "category": "Diabetes",
        "price": 28.00,
        "description": "First-line medication for type 2 diabetes management.",
        "image_url": "https://images.unsplash.com/photo-1576671081837-49000212a370?w=300&q=80",
        "in_stock": True,
        "requires_prescription": True,
        "quantity_available": 70,
    },
    {
        "id": "m9",
        "name": "Cetirizine 10mg",
        "category": "Allergy",
        "price": 15.00,
        "description": "Antihistamine for allergy relief. Non-drowsy formula for hay fever and hives.",
        "image_url": "https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=300&q=80",
        "in_stock": True,
        "requires_prescription": False,
        "quantity_available": 110,
    },
    {
        "id": "m10",
        "name": "Omega-3 Fish Oil",
        "category": "Supplements",
        "price": 60.00,
        "description": "High-quality omega-3 fatty acids for heart and brain health. 60 capsules.",
        "image_url": "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=300&q=80",
        "in_stock": True,
        "requires_prescription": False,
        "quantity_available": 50,
    },
    {
        "id": "m11",
        "name": "Aspirin 100mg",
        "category": "Pain Relief",
        "price": 8.50,
        "description": "Low-dose aspirin for heart protection and pain relief. Enteric-coated.",
        "image_url": "https://images.unsplash.com/photo-1585435557343-3b348031e799?w=300&q=80",
        "in_stock": True,
        "requires_prescription": False,
        "quantity_available": 200,
    },
    {
        "id": "m12",
        "name": "Lisinopril 10mg",
        "category": "Diabetes",
        "price": 45.00,
        "description": "ACE inhibitor for high blood pressure and heart failure management.",
        "image_url": "https://images.unsplash.com/photo-1517021897933-0e0319cfbc28?w=300&q=80",
        "in_stock": True,
        "requires_prescription": True,
        "quantity_available": 55,
    },
    {
        "id": "m13",
        "name": "Loratadine 10mg",
        "category": "Allergy",
        "price": 20.00,
        "description": "24-hour non-drowsy antihistamine for seasonal allergies and hives.",
        "image_url": "https://images.unsplash.com/photo-1607619662634-3ac55ec0e3c4?w=300&q=80",
        "in_stock": True,
        "requires_prescription": False,
        "quantity_available": 130,
    },
    {
        "id": "m14",
        "name": "Vitamin B Complex",
        "category": "Vitamins",
        "price": 35.00,
        "description": "Complete B-vitamin formula for energy, nerve function, and metabolism.",
        "image_url": "https://images.unsplash.com/photo-1579154341184-a7bc88c5a18a?w=300&q=80",
        "in_stock": True,
        "requires_prescription": False,
        "quantity_available": 90,
    },
    {
        "id": "m15",
        "name": "Magnesium 400mg",
        "category": "Supplements",
        "price": 55.00,
        "description": "Essential mineral supplement for muscle relaxation, sleep, and energy production.",
        "image_url": "https://images.unsplash.com/photo-1516574187841-cb9cc2ca948b?w=300&q=80",
        "in_stock": True,
        "requires_prescription": False,
        "quantity_available": 75,
    },
    {
        "id": "m16",
        "name": "Antacid Tablets",
        "category": "Digestive",
        "price": 14.00,
        "description": "Fast-acting antacid for heartburn, acid indigestion, and upset stomach relief.",
        "image_url": "https://images.unsplash.com/photo-1583912267550-d44c9b4b5e94?w=300&q=80",
        "in_stock": True,
        "requires_prescription": False,
        "quantity_available": 160,
    },
    {
        "id": "m17",
        "name": "Zinc 50mg",
        "category": "Supplements",
        "price": 30.00,
        "description": "Immune support mineral. Essential for wound healing and immune function.",
        "image_url": "https://images.unsplash.com/photo-1578496780895-d31e9fbf3db4?w=300&q=80",
        "in_stock": True,
        "requires_prescription": False,
        "quantity_available": 100,
    },
    {
        "id": "m18",
        "name": "Ciprofloxacin 500mg",
        "category": "Antibiotics",
        "price": 65.00,
        "description": "Broad-spectrum antibiotic for urinary tract, respiratory, and skin infections.",
        "image_url": "https://images.unsplash.com/photo-1563213126-a4273aed2016?w=300&q=80",
        "in_stock": True,
        "requires_prescription": True,
        "quantity_available": 30,
    },
    {
        "id": "m19",
        "name": "Insulin Glargine",
        "category": "Diabetes",
        "price": 180.00,
        "description": "Long-acting basal insulin for type 1 and type 2 diabetes. Once-daily injection.",
        "image_url": "https://images.unsplash.com/photo-1631549916768-4119b2e5f926?w=300&q=80",
        "in_stock": False,
        "requires_prescription": True,
        "quantity_available": 0,
    },
    {
        "id": "m20",
        "name": "Probiotic Complex",
        "category": "Digestive",
        "price": 85.00,
        "description": "10 billion CFU probiotic for gut health, digestion, and immune support. 30 capsules.",
        "image_url": "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=300&q=80",
        "in_stock": True,
        "requires_prescription": False,
        "quantity_available": 45,
    },
]
